title: "Nyanga P - DevOps and Cloud Engineer Portfolio"
description: "Professional portfolio of Nyanga P showcasing skills, tools, experience, and contact information."
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM
