name: Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Create auth.js
      run: |
        echo "(function() {" > _site/auth.js
        echo "  var user = '${{ secrets.AUTH_USERNAME }}';" >> _site/auth.js
        echo "  var password = '${{ secrets.AUTH_PASSWORD }}';" >> _site/auth.js
        echo "  var authPrompt = function() {" >> _site/auth.js
        echo "    var enteredUser = prompt('Enter Username:');" >> _site/auth.js
        echo "    var enteredPassword = prompt('Enter Password:');" >> _site/auth.js
        echo "    return enteredUser === user && enteredPassword === password;" >> _site/auth.js
        echo "  };" >> _site/auth.js
        echo "  if (!authPrompt()) {" >> _site/auth.js
        echo "    document.body.innerHTML = '<h1>Unauthorized Access</h1>';" >> _site/auth.js
        echo "  }" >> _site/auth.js
        echo "})();" >> _site/auth.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site



